version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: systeminfo
      - run:
         command: wget https://mirror.koddos.net/apache/hadoop/common/hadoop-3.2.2/hadoop-3.2.2-src.tar.gz -O hadoop-3.2.2-src.tar.gz
         shell: bash.exe
      - run:
         command: tar -zxf hadoop-3.2.2-src.tar.gz
         shell: bash.exe
      - run:
         command: ls -lh
         shell: bash.exe
   
